routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('home');
/*Route::get('/', function () {
    return view('welcome');
});*/

Route::resource('posts', PostController::class);
Auth::routes();
Route::post('/loginajx', [App\Http\Controllers\Auth\CustomLoginController::class, 'loginUser']);
Route::post('/singupajx', [App\Http\Controllers\Auth\CustomSingupController::class, 'registerUser']);

Route::group(['middleware' => 'auth'], function () {
	Route::post('loadimage', [AccountController::class, 'loadImage']);
	Route::post('upimage', [AccountController::class, 'upImage']);
	Route::post('upprofile', [AccountController::class, 'update']);
	Route::post('delimage', [AccountController::class, 'delImage']);
	Route::post('uppassword', [AccountController::class, 'upPassword']);
	Route::resource('account', AccountController::class, ['parameters' => ['account' => 'user']]);
});

resources/views/layouts/app-auth.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
@section('title', 'Inicio')
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" type="image/png" href="{{ asset('public/app/images/favicon.png') }}"/>
		<title>{{ config('app.name', 'Hogar') }} - @yield('title')</title></title>
		<!-- CSS only -->
		<link rel="stylesheet" href="{{asset('public/vendor/bootstrap/css/animate.css')}}">
		<link rel="stylesheet" href="{{asset('public/vendor/bootstrap/css/animation.css')}}">
		<link rel="stylesheet" href="{{asset('public/vendor/bootstrap-icons/bootstrap-icons.css')}}">
		<link rel="stylesheet" href="{{asset('public/vendor/bootstrap/css/bootstrap.min.css')}}">
		<link rel="stylesheet" href="{{asset('public/vendor/font-awesome/css/all.css')}}">
		<link href="{{asset('public/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('public/app/css/custom.css')}}" rel="stylesheet">
		<script src="{{asset('public/vendor/jquery/jquery-3.6.0.min.js')}}"></script>
		<script src="{{asset('public/vendor/notify/notify-custom.js')}}"></script>
		<link rel="stylesheet" href="{{asset('public/vendor/lightbox/lightbox.css')}}">
		<meta name="csrf-token" content="{{ csrf_token() }}"/>
	</head>
	<body>
		@include('layouts.navbar')
		<div id="app">
			<main class="py-4">
				@yield('content')
			</main>
		</div>

		@include('layouts.footer')

		<script>
			window.jQuery || document.write('<script src="{{asset("public/vendor/jquery/jquery-3.6.0.min.js")}}"><\/script>')
		</script>
		<script src="{{asset('public/vendor/jquery/jquery-3.6.0.min.js')}}"></script>

		<!-- Scripts for bootstrap 4.3.1-->
		<!--script src="{{asset('public/vendor/bootstrap/js/feather.min.js')}}"></script-->
		<script src="{{asset('public/vendor/bootstrap/js/popper.min.js')}}"></script>
		<script src="{{asset('public/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
		<script src="{{asset('public/vendor/bootstrap/js/jquery.sharrre.js')}}"></script>
		<script src="{{asset('public/vendor/bootstrap/js/ie10-viewport-bug-workaround.js')}}"></script>
		<script src="{{asset('public/app/js/footer.js')}}"></script>
		<script src="https://www.google.com/recaptcha/api.js"></script>
		<script src="{{asset('public/vendor/mask/jquery.mask.min.js')}}"></script>

		<script src="{{asset('public/vendor/lightbox/lightbox.js')}}"></script>
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{{asset('public/vendor/bootstrap-notify/bootstrap-notify.min.js')}}"></script>
		<script src="{{asset('public/vendor/bootstrap-notify/fun_msg.js')}}"></script>
		
		<script type="text/javascript">
			$(document).ready(function(){
				$(window).scroll(function(){
					if($(this).scrollTop() > 100){
						$('#scroll').fadeIn();
					}else{
						$('#scroll').fadeOut();
					}
				});
				$('#scroll').click(function(){
					$("html, body").animate({ scrollTop: 0 }, 600);
					return false;
				});

				var url = document.location.toString();
				if (url.match('#')) {
					$('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
				}
				$('.nav-tabs a').on('shown.bs.tab', function (e) {
					let stateObj = { id: "100" };
					window.history.replaceState(stateObj,"Page 3", e.target.hash);
				});
			});
		</script>
		<script type="text/javascript">
			$('.dropdown .dropdown-menu').on('click', function(event){
				event.stopPropagation();
			});
			$('.no-cerrar .dropdown-menu').on('click', function(event){
				event.stopPropagation();
			});
		</script>
	</body>
</html>

resources/views/layouts/footer.blade.php
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p class="text-center">
					Copyright @2020 | Designed & Development by <a href="https://linuxitos.com/">LuNuXiToS</a>
				</p>
			</div>
		</div>
	</div>
</footer>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Eighth navbar example">
	<div class="container">
		<a class="navbar-brand" href="{{url('/')}}">
			<img class="img-fluid" src="{{asset('public/app/images/logo_navbar.svg')}}" id="logo_custom"  alt="logo" width="100">
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" onclick="sitepoint.SidebarNav_toggle(event);" onkeyup="sitepoint.SidebarNav_toggle(event);">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarsExample07">
			<ul class="navbar-nav flex-row flex-wrap ms-md-auto">
				<li class="nav-item col-6 col-md-auto">
					<a class="nav-link {{request()->is('/')?'active':''}}" href="{{url('/')}}">Inicio</a>
				</li>
				<li class="nav-item col-6 col-md-auto">
					<a class="nav-link" href="https://linuxitos.com/blog/about">About</a>
				</li>
				<li class="nav-item col-6 col-md-auto">
					<a class="nav-link" href="https://linuxitos.com/blog/servicios">Services</a>
				</li>
				<li class="nav-item col-6 col-md-auto">
					<a class="nav-link" href="https://linuxitos.com/blog/contacto">Contact</a>
				</li>
				<li class="nav-item col-6 col-md-auto dropdown desplegable">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-bs-toggle="dropdown" aria-expanded="false">Tutoriales</a>
					<div class="dropdown-menu dropdown-menu-end desplegable-menu" aria-labelledby="dropdown07">
						<a class="dropdown-item" href="{{url('pageajax')}}">
							Paginación con ajax
						</a>
						<a class="dropdown-item" href="{{url('pagenotajax')}}">
							Paginación sin ajax
						</a>
						<a class="dropdown-item" href="{{url('scroll')}}">
							Scroll
						</a>
						<a class="dropdown-item" href="{{url('docs')}}">
							Docs
						</a>
					</div>
				</li>

				@if (auth()->check())
					<li class="nav-item col-6 col-md-auto dropdown desplegable">
						<a class="nav-link dropdown-toggle" href="#" id="menu-options" data-bs-toggle="dropdown" role="button" aria-expanded="false">
							<span class="pull-left">
								<img src="{{(auth()->user()->image!='' && file_exists(public_path(auth()->user()->files.auth()->user()->image)) ? asset('public/'.auth()->user()->files.auth()->user()->image): asset('public/images/default.svg'))}}" class="img-circle rounded-circle bg-white" title="Imagen user" alt="Imagen user" width="30px" height="30px"> {{auth()->user()->name}}
							</span>
							<span class="caret"></span>
						</a>
						<div class="dropdown-menu dropdown-menu-end desplegable-menu div-menu" aria-labelledby="menu-options">
							<a class="dropdown-item {{request()->is('account')?'active':''}}" href="{{route('account.index')}}">
								Perfil <i class="bi bi-person float-end"></i>
							</a>
							<a class="dropdown-item" href="{{url('ptables')}}">
								Tablas con Ajax <i class="bi bi-table float-end"></i>
							</a>
							<a class="dropdown-item" href="{{url('ptablesnjx')}}">
								Tablas sin Ajax <i class="bi bi-table float-end"></i>
							</a>
							<a class="dropdown-item" href="{{url('upimages')}}">
								Subir imágenes <i class="bi bi-images float-end"></i>
							</a>
							<a class="dropdown-item" href="{{url('dragdrop')}}">
								Drag & Drop <i class="bi bi-files float-end"></i>
							</a>
							<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
								Salir <i class="bi bi-box-arrow-right float-end"></i>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
						</div>
					</li>
				@endif
			</ul>
			@guest
				@if(!request()->is('register'))
					<a class="my-2 my-md-0 ms-md-3 me-2 btn btn-outline-warning" href="{{url('register')}}">
						Registro
					</a>
				@endif
				@if(!request()->is('login'))
					<a class="btn btn-outline-primary" href="{{url('login')}}">
						Iniciar Sesión
					</a>
				@endif
			@endguest
		</div>
	</div>
</nav>